# Pull base image.
FROM ubuntu:18.04
MAINTAINER ghjjhg567

ARG DEBIAN_FRONTEND=noninteractive
ENV TERM linux

RUN \
  apt-get update ; \
  apt-get -y install git python3 python3-dev python3-setuptools python3-pip && \
  apt-get -y install python python-dev python-setuptools python-pip && \
  apt-get -y install build-essential libffi-dev && \
  apt-get -y install libpq-dev vim  libssl-dev && \
  apt-get -y install libxml2-dev libxslt1-dev && \
  apt-get -y install libmysqlclient-dev && \
  apt-get -y install wget software-properties-common && \
  apt-get -y install gcc
