version: '3'
services:
    mongo:
      container_name: mongo
      image: mongo
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password
        MONGO_INITDB_DATABASE: test
      volumes:
        - ./mongo/001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
        - ./mongo-volume:/data/db
      restart: always
      networks:
        - backend-bridge

    mongo-express:
      container_name: mongo-express
      image: mongo-express
      ports:
        - "8081:8081"
      environment:
        ME_CONFIG_MONGODB_AUTH_DATABASE: admin
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: password
        ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
        ME_CONFIG_BASICAUTH_USERNAME: root
        ME_CONFIG_BASICAUTH_PASSWORD: password
      restart: always
      depends_on:
        - mongo
      networks:
        - backend-bridge

    sif:
      container_name: sif
      image: sif:latest
      build:
        context: ../../
        dockerfile: Dockerfile_test
      command: supervisord -n
      ports:
        - "8700:8700"
      volumes:
        - ../../.:/usr/src/app/
      environment:
        CONFIG_PATH: /usr/src/app/deployment/local/local.conf
      env_file:
        - ./local.conf
      logging:
        driver: "json-file"
        options:
          max-size: "50m"
      restart: always
      depends_on:
        - mongo
      networks:
        - backend-bridge

    nginx:
      container_name: nginx
      image: nginx
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ../../nginx/nginx.conf:/etc/nginx/nginx.conf
        - ../../nginx/default.conf:/etc/nginx/conf.d/default.conf
      restart: always
      depends_on:
        - sif
      networks:
        - backend-bridge

networks:
  backend-bridge:
    driver: bridge
